'''
inspectOriginHeaderScrutiny.py
'''

from core.controllers.basePlugin.baseAuditPlugin import baseAuditPlugin
from core.data.options.optionList import optionList
from core.data.options.option import option
from core.data.constants import httpConstants
from core.controllers.w3afException import w3afException
import urllib2
import random
import core.controllers.outputManager as om
import core.data.kb.knowledgeBase as kb
import core.data.kb.vuln as vuln
import core.data.constants.severity as severity

class inspectOriginHeaderScrutiny(baseAuditPlugin):
    '''
    Inspect if application check that the value of the "Origin" HTTP header is consistent with the value 
    of the remote IP address/Host of the sender of the incoming HTTP request.
      
    @author: Dominique RIGHETTO (dominique.righetto@owasp.org)     
    '''

    def __init__(self):
        '''
        Class constructor
        '''
        baseAuditPlugin.__init__(self)
        #Define plugin options configuration variables
        self.debug = False
        self.originHeaderValue = "http://w3af.sourceforge.net"
        self.expectedHttpResponseCode = httpConstants.OK
        
    def audit(self, freq):
        '''
        Plugin entry point.

        @param freq: A fuzzableRequest
        ''' 
        
        #Get current URL object
        url = freq.getURL()
                
        #Try to send a forged HTTP request in order to test target application behavior
        try:
            #Build request content
            forgedReq = urllib2.Request(url.url_string)
            forgedReq.add_header("User-Agent", "W3AF")
            forgedReq.add_header("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
            forgedReq.add_header("Accept-Language", "en-us,en;q=0.5")
            forgedReq.add_header("Accept-Charset", "ISO-8859-1,utf-8;q=0.7,*;q=0.7")
            forgedReq.add_header("Origin", self.originHeaderValue.strip())
            #Sent request and analyze response
            if(self.debug):
                dLevel = 1
            else:
                dLevel = 0                                
            #--Sent request
            httpHandler = urllib2.HTTPHandler(debuglevel=dLevel)
            opener = urllib2.build_opener(httpHandler)
            response = opener.open(forgedReq)
            responseCode = response.getcode()
            opener.close() 
            #Analyze response
            if responseCode == self.expectedHttpResponseCode:
                v = vuln.vuln()
                v.setSeverity(severity.MEDIUM)
                v.setPluginName(self.getName())
                v.setName('Inspect Origin Header Scrutiny')
                v.setURL(url)
                v.setId(random.randint(1, 100) * random.randint(1, 100))
                msg = 'Application seems to reply correctly event if it tampers with the "Origin" HTTP header.'
                v.setDesc(msg)
                kb.kb.append(self , 'inspectOriginHeaderScrutiny' , v)                 
        except Exception, e:
            #Manage error       
            om.out.error('Error in audit.inspectOriginHeaderScrutiny: "' + repr(e) + '".')
                                
    def getOptions(self):
        '''
        @return: A list of option objects for this plugin.
        '''
        ol = optionList()
        d1 = "Debug mode"
        h1 = "If set to True, w3af will print HTTP request/response exchanges with target application"
        o1 = option('debug', self.debug, d1, "boolean", help=h1)        
        ol.add(o1)
        d2 = "Origin HTTP header value"
        h2 = "Define value used to specify the 'Origin' HTTP header for HTTP request sent to test application behavior"
        o2 = option('originHeaderValue', self.originHeaderValue, d2, "string", help=h2)        
        ol.add(o2)        
        d3 = "Expected HTTP response code from application for normal case"
        h3 = "Define the HTTP response code that the application return when it have successfully processed a HTTP request"
        o3 = option('expectedHttpResponseCode', self.expectedHttpResponseCode, d3, "integer", help=h3)        
        ol.add(o3)                
        return ol

    def setOptions(self, optionList):
        '''
        This method sets all the options that are configured using the user interface 
        generated by the framework using the result of getOptions().usefull

        @parameter OptionList: A dictionary with the options for the plugin.
        @return: No value is returned.
        '''
        self.debug = optionList['debug'].getValue()
        self.originHeaderValue = optionList['originHeaderValue'].getValue()
        self.expectedHttpResponseCode = optionList['expectedHttpResponseCode'].getValue()   
        #Check options setted
        if self.expectedHttpResponseCode < 100 or self.expectedHttpResponseCode > 505:
            msg = 'Please enter a valid HTTP response code (see valid code list on "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html") !'
            raise w3afException(msg)
        if self.originHeaderValue is None or len(self.originHeaderValue.strip()) == 0 :
            msg = 'Please enter a valid value for the "Origin" HTTP header !'
            raise w3afException(msg)                         

    def getPluginDeps(self):
        '''
        @return: A list with the names of the plugins that should be runned before the
        current one.
        '''
        return []

    def getLongDesc(self):
        '''
        @return: A DETAILED description of the plugin functions and features.
        '''
        return '''
        Inspect if application check that the value of the "Origin" HTTP header is consistent with the value 
        of the remote IP address/Host of the sender of the incoming HTTP request.
        
        Configurable parameters are:
            - debug
            - originHeaderValue
            - expectedHttpResponseCode      
      
        Note : This plugin is useful to test "Cross Origin Resource Sharing (CORS)" application behaviors.
        CORS : http://developer.mozilla.org/en-US/docs/HTTP_access_control
               http://www.w3.org/TR/cors
        '''
