INSERT INTO "MYTESTUSER"."DEVELOPER_EMPLOYER" (ID_EMPLOYER,NAME_EMPLOYER) VALUES (1,'LOGICA');
INSERT INTO "MYTESTUSER"."DEVELOPER_EMPLOYER" (ID_EMPLOYER,NAME_EMPLOYER) VALUES (2,'SOGETI');
INSERT INTO "MYTESTUSER"."DEVELOPER_EMPLOYER" (ID_EMPLOYER,NAME_EMPLOYER) VALUES (3,'CTG');
INSERT INTO "MYTESTUSER"."DEVELOPER_EMPLOYER" (ID_EMPLOYER,NAME_EMPLOYER) VALUES (4,'PWC');


INSERT INTO "MYTESTUSER"."DEVELOPER_LEVEL" (ID_LEVEL,LABEL_LEVEL) VALUES (1,'BEGINNER');
INSERT INTO "MYTESTUSER"."DEVELOPER_LEVEL" (ID_LEVEL,LABEL_LEVEL) VALUES (2,'MIDDLE');
INSERT INTO "MYTESTUSER"."DEVELOPER_LEVEL" (ID_LEVEL,LABEL_LEVEL) VALUES (3,'EXPERT');

INSERT INTO "MYTESTUSER"."DEVELOPER" (ID_DEVELOPER,NAME_DEVELOPER,ID_DEVELOPER_LEVEL,ID_DEVELOPER_EMPLOYER) VALUES (1,'RIGHETTO',1,1);
INSERT INTO "MYTESTUSER"."DEVELOPER" (ID_DEVELOPER,NAME_DEVELOPER,ID_DEVELOPER_LEVEL,ID_DEVELOPER_EMPLOYER) VALUES (2,'FANCZALSKI',1,2);
INSERT INTO "MYTESTUSER"."DEVELOPER" (ID_DEVELOPER,NAME_DEVELOPER,ID_DEVELOPER_LEVEL,ID_DEVELOPER_EMPLOYER) VALUES (3,'COUSIN',2,3);
INSERT INTO "MYTESTUSER"."DEVELOPER" (ID_DEVELOPER,NAME_DEVELOPER,ID_DEVELOPER_LEVEL,ID_DEVELOPER_EMPLOYER) VALUES (4,'MORONVAL',3,4);
