//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-325 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.16 at 09:04:51 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hikage.be/schema/traduction", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.hikage.spring.ws.jaxb.dto;
