//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-325 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.11.16 at 09:04:51 PM CET 
//


package be.hikage.spring.ws.jaxb.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TraductionRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TraductionRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="langueOrigine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="langueDestination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="texte" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TraductionRequestType", propOrder = {
    "langueOrigine",
    "langueDestination",
    "texte"
})
public class TraductionRequestType {

    @XmlElement(required = true)
    protected String langueOrigine;
    @XmlElement(required = true)
    protected String langueDestination;
    @XmlElement(required = true)
    protected String texte;

    /**
     * Gets the value of the langueOrigine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangueOrigine() {
        return langueOrigine;
    }

    /**
     * Sets the value of the langueOrigine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangueOrigine(String value) {
        this.langueOrigine = value;
    }

    /**
     * Gets the value of the langueDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangueDestination() {
        return langueDestination;
    }

    /**
     * Sets the value of the langueDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangueDestination(String value) {
        this.langueDestination = value;
    }

    /**
     * Gets the value of the texte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTexte() {
        return texte;
    }

    /**
     * Sets the value of the texte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTexte(String value) {
        this.texte = value;
    }

}
