<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://ajaxtags.org/tags/ajax" prefix="ajax" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>
<c:set var="contextPath" scope="request">${pageContext.request.contextPath}</c:set>
<head>
  <title>Multithread</title>
  <script type="text/javascript" src="${contextPath}/js/prototype-1.4.0.js"></script>
  <script type="text/javascript" src="${contextPath}/js/scriptaculous.js"></script>
  <script type="text/javascript" src="${contextPath}/js/overlibmws.js"></script>
  <script type="text/javascript" src="${contextPath}/js/ajaxtags.js"></script> 
   <script type="text/javascript">     
      function check()
      {
         for( i = 0 ; i < 100 ; i++ )
          {
              j = document.getElementById("testPortlet" + i + "Content").innerHTML;                            
              if( (j != "" ) && (j != i) ) 
                 alert("error on component : " + j); 
              else
                 window.status = "Check portlet [" + i + "] = [" + j + "]";              
                 
          }            
          setTimeout("check()", 1000);
      }
   </script>
  <link type="text/css" rel="stylesheet" href="${contextPath}/css/ajax.css" />
</head>
<body onload="check()">
<div id="portletArea0"><ajax:portlet var="testP0" source="testPortlet0" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=0" classNamePrefix="portlet" title="Multithread object 0" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea1"><ajax:portlet var="testP1" source="testPortlet1" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=1" classNamePrefix="portlet" title="Multithread object 1" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea2"><ajax:portlet var="testP2" source="testPortlet2" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=2" classNamePrefix="portlet" title="Multithread object 2" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea3"><ajax:portlet var="testP3" source="testPortlet3" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=3" classNamePrefix="portlet" title="Multithread object 3" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea4"><ajax:portlet var="testP4" source="testPortlet4" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=4" classNamePrefix="portlet" title="Multithread object 4" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea5"><ajax:portlet var="testP5" source="testPortlet5" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=5" classNamePrefix="portlet" title="Multithread object 5" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea6"><ajax:portlet var="testP6" source="testPortlet6" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=6" classNamePrefix="portlet" title="Multithread object 6" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea7"><ajax:portlet var="testP7" source="testPortlet7" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=7" classNamePrefix="portlet" title="Multithread object 7" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea8"><ajax:portlet var="testP8" source="testPortlet8" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=8" classNamePrefix="portlet" title="Multithread object 8" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea9"><ajax:portlet var="testP9" source="testPortlet9" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=9" classNamePrefix="portlet" title="Multithread object 9" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea10"><ajax:portlet var="testP10" source="testPortlet10" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=10" classNamePrefix="portlet" title="Multithread object 10" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea11"><ajax:portlet var="testP11" source="testPortlet11" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=11" classNamePrefix="portlet" title="Multithread object 11" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea12"><ajax:portlet var="testP12" source="testPortlet12" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=12" classNamePrefix="portlet" title="Multithread object 12" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea13"><ajax:portlet var="testP13" source="testPortlet13" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=13" classNamePrefix="portlet" title="Multithread object 13" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea14"><ajax:portlet var="testP14" source="testPortlet14" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=14" classNamePrefix="portlet" title="Multithread object 14" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea15"><ajax:portlet var="testP15" source="testPortlet15" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=15" classNamePrefix="portlet" title="Multithread object 15" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea16"><ajax:portlet var="testP16" source="testPortlet16" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=16" classNamePrefix="portlet" title="Multithread object 16" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea17"><ajax:portlet var="testP17" source="testPortlet17" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=17" classNamePrefix="portlet" title="Multithread object 17" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea18"><ajax:portlet var="testP18" source="testPortlet18" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=18" classNamePrefix="portlet" title="Multithread object 18" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea19"><ajax:portlet var="testP19" source="testPortlet19" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=19" classNamePrefix="portlet" title="Multithread object 19" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea20"><ajax:portlet var="testP20" source="testPortlet20" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=20" classNamePrefix="portlet" title="Multithread object 20" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea21"><ajax:portlet var="testP21" source="testPortlet21" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=21" classNamePrefix="portlet" title="Multithread object 21" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea22"><ajax:portlet var="testP22" source="testPortlet22" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=22" classNamePrefix="portlet" title="Multithread object 22" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea23"><ajax:portlet var="testP23" source="testPortlet23" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=23" classNamePrefix="portlet" title="Multithread object 23" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea24"><ajax:portlet var="testP24" source="testPortlet24" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=24" classNamePrefix="portlet" title="Multithread object 24" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea25"><ajax:portlet var="testP25" source="testPortlet25" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=25" classNamePrefix="portlet" title="Multithread object 25" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea26"><ajax:portlet var="testP26" source="testPortlet26" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=26" classNamePrefix="portlet" title="Multithread object 26" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea27"><ajax:portlet var="testP27" source="testPortlet27" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=27" classNamePrefix="portlet" title="Multithread object 27" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea28"><ajax:portlet var="testP28" source="testPortlet28" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=28" classNamePrefix="portlet" title="Multithread object 28" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea29"><ajax:portlet var="testP29" source="testPortlet29" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=29" classNamePrefix="portlet" title="Multithread object 29" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea30"><ajax:portlet var="testP30" source="testPortlet30" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=30" classNamePrefix="portlet" title="Multithread object 30" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea31"><ajax:portlet var="testP31" source="testPortlet31" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=31" classNamePrefix="portlet" title="Multithread object 31" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea32"><ajax:portlet var="testP32" source="testPortlet32" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=32" classNamePrefix="portlet" title="Multithread object 32" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea33"><ajax:portlet var="testP33" source="testPortlet33" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=33" classNamePrefix="portlet" title="Multithread object 33" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea34"><ajax:portlet var="testP34" source="testPortlet34" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=34" classNamePrefix="portlet" title="Multithread object 34" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea35"><ajax:portlet var="testP35" source="testPortlet35" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=35" classNamePrefix="portlet" title="Multithread object 35" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea36"><ajax:portlet var="testP36" source="testPortlet36" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=36" classNamePrefix="portlet" title="Multithread object 36" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea37"><ajax:portlet var="testP37" source="testPortlet37" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=37" classNamePrefix="portlet" title="Multithread object 37" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea38"><ajax:portlet var="testP38" source="testPortlet38" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=38" classNamePrefix="portlet" title="Multithread object 38" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea39"><ajax:portlet var="testP39" source="testPortlet39" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=39" classNamePrefix="portlet" title="Multithread object 39" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea40"><ajax:portlet var="testP40" source="testPortlet40" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=40" classNamePrefix="portlet" title="Multithread object 40" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea41"><ajax:portlet var="testP41" source="testPortlet41" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=41" classNamePrefix="portlet" title="Multithread object 41" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea42"><ajax:portlet var="testP42" source="testPortlet42" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=42" classNamePrefix="portlet" title="Multithread object 42" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea43"><ajax:portlet var="testP43" source="testPortlet43" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=43" classNamePrefix="portlet" title="Multithread object 43" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea44"><ajax:portlet var="testP44" source="testPortlet44" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=44" classNamePrefix="portlet" title="Multithread object 44" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea45"><ajax:portlet var="testP45" source="testPortlet45" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=45" classNamePrefix="portlet" title="Multithread object 45" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea46"><ajax:portlet var="testP46" source="testPortlet46" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=46" classNamePrefix="portlet" title="Multithread object 46" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea47"><ajax:portlet var="testP47" source="testPortlet47" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=47" classNamePrefix="portlet" title="Multithread object 47" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea48"><ajax:portlet var="testP48" source="testPortlet48" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=48" classNamePrefix="portlet" title="Multithread object 48" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea49"><ajax:portlet var="testP49" source="testPortlet49" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=49" classNamePrefix="portlet" title="Multithread object 49" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea50"><ajax:portlet var="testP50" source="testPortlet50" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=50" classNamePrefix="portlet" title="Multithread object 50" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea51"><ajax:portlet var="testP51" source="testPortlet51" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=51" classNamePrefix="portlet" title="Multithread object 51" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea52"><ajax:portlet var="testP52" source="testPortlet52" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=52" classNamePrefix="portlet" title="Multithread object 52" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea53"><ajax:portlet var="testP53" source="testPortlet53" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=53" classNamePrefix="portlet" title="Multithread object 53" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea54"><ajax:portlet var="testP54" source="testPortlet54" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=54" classNamePrefix="portlet" title="Multithread object 54" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea55"><ajax:portlet var="testP55" source="testPortlet55" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=55" classNamePrefix="portlet" title="Multithread object 55" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea56"><ajax:portlet var="testP56" source="testPortlet56" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=56" classNamePrefix="portlet" title="Multithread object 56" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea57"><ajax:portlet var="testP57" source="testPortlet57" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=57" classNamePrefix="portlet" title="Multithread object 57" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea58"><ajax:portlet var="testP58" source="testPortlet58" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=58" classNamePrefix="portlet" title="Multithread object 58" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea59"><ajax:portlet var="testP59" source="testPortlet59" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=59" classNamePrefix="portlet" title="Multithread object 59" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea60"><ajax:portlet var="testP60" source="testPortlet60" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=60" classNamePrefix="portlet" title="Multithread object 60" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea61"><ajax:portlet var="testP61" source="testPortlet61" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=61" classNamePrefix="portlet" title="Multithread object 61" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea62"><ajax:portlet var="testP62" source="testPortlet62" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=62" classNamePrefix="portlet" title="Multithread object 62" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea63"><ajax:portlet var="testP63" source="testPortlet63" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=63" classNamePrefix="portlet" title="Multithread object 63" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea64"><ajax:portlet var="testP64" source="testPortlet64" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=64" classNamePrefix="portlet" title="Multithread object 64" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea65"><ajax:portlet var="testP65" source="testPortlet65" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=65" classNamePrefix="portlet" title="Multithread object 65" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea66"><ajax:portlet var="testP66" source="testPortlet66" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=66" classNamePrefix="portlet" title="Multithread object 66" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea67"><ajax:portlet var="testP67" source="testPortlet67" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=67" classNamePrefix="portlet" title="Multithread object 67" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea68"><ajax:portlet var="testP68" source="testPortlet68" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=68" classNamePrefix="portlet" title="Multithread object 68" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea69"><ajax:portlet var="testP69" source="testPortlet69" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=69" classNamePrefix="portlet" title="Multithread object 69" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea70"><ajax:portlet var="testP70" source="testPortlet70" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=70" classNamePrefix="portlet" title="Multithread object 70" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea71"><ajax:portlet var="testP71" source="testPortlet71" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=71" classNamePrefix="portlet" title="Multithread object 71" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea72"><ajax:portlet var="testP72" source="testPortlet72" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=72" classNamePrefix="portlet" title="Multithread object 72" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea73"><ajax:portlet var="testP73" source="testPortlet73" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=73" classNamePrefix="portlet" title="Multithread object 73" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea74"><ajax:portlet var="testP74" source="testPortlet74" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=74" classNamePrefix="portlet" title="Multithread object 74" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea75"><ajax:portlet var="testP75" source="testPortlet75" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=75" classNamePrefix="portlet" title="Multithread object 75" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea76"><ajax:portlet var="testP76" source="testPortlet76" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=76" classNamePrefix="portlet" title="Multithread object 76" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea77"><ajax:portlet var="testP77" source="testPortlet77" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=77" classNamePrefix="portlet" title="Multithread object 77" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea78"><ajax:portlet var="testP78" source="testPortlet78" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=78" classNamePrefix="portlet" title="Multithread object 78" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea79"><ajax:portlet var="testP79" source="testPortlet79" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=79" classNamePrefix="portlet" title="Multithread object 79" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea80"><ajax:portlet var="testP80" source="testPortlet80" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=80" classNamePrefix="portlet" title="Multithread object 80" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea81"><ajax:portlet var="testP81" source="testPortlet81" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=81" classNamePrefix="portlet" title="Multithread object 81" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea82"><ajax:portlet var="testP82" source="testPortlet82" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=82" classNamePrefix="portlet" title="Multithread object 82" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea83"><ajax:portlet var="testP83" source="testPortlet83" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=83" classNamePrefix="portlet" title="Multithread object 83" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea84"><ajax:portlet var="testP84" source="testPortlet84" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=84" classNamePrefix="portlet" title="Multithread object 84" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea85"><ajax:portlet var="testP85" source="testPortlet85" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=85" classNamePrefix="portlet" title="Multithread object 85" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea86"><ajax:portlet var="testP86" source="testPortlet86" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=86" classNamePrefix="portlet" title="Multithread object 86" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea87"><ajax:portlet var="testP87" source="testPortlet87" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=87" classNamePrefix="portlet" title="Multithread object 87" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea88"><ajax:portlet var="testP88" source="testPortlet88" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=88" classNamePrefix="portlet" title="Multithread object 88" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea89"><ajax:portlet var="testP89" source="testPortlet89" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=89" classNamePrefix="portlet" title="Multithread object 89" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea90"><ajax:portlet var="testP90" source="testPortlet90" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=90" classNamePrefix="portlet" title="Multithread object 90" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea91"><ajax:portlet var="testP91" source="testPortlet91" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=91" classNamePrefix="portlet" title="Multithread object 91" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea92"><ajax:portlet var="testP92" source="testPortlet92" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=92" classNamePrefix="portlet" title="Multithread object 92" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea93"><ajax:portlet var="testP93" source="testPortlet93" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=93" classNamePrefix="portlet" title="Multithread object 93" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea94"><ajax:portlet var="testP94" source="testPortlet94" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=94" classNamePrefix="portlet" title="Multithread object 94" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea95"><ajax:portlet var="testP95" source="testPortlet95" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=95" classNamePrefix="portlet" title="Multithread object 95" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea96"><ajax:portlet var="testP96" source="testPortlet96" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=96" classNamePrefix="portlet" title="Multithread object 96" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea97"><ajax:portlet var="testP97" source="testPortlet97" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=97" classNamePrefix="portlet" title="Multithread object 97" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea98"><ajax:portlet var="testP98" source="testPortlet98" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=98" classNamePrefix="portlet" title="Multithread object 98" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
<div id="portletArea99"><ajax:portlet var="testP99" source="testPortlet99" baseUrl="${contextPath}/ajax/askAnswer.do" parameters="id=99" classNamePrefix="portlet" title="Multithread object 99" imageClose="${contextPath}/img/close.png" imageMaximize="${contextPath}/img/maximize.png" imageMinimize="${contextPath}/img/minimize.png" imageRefresh="${contextPath}/img/refresh.png" refreshPeriod="2" /></div><br>
</body> 
</html>
