//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 08:06:23 PM CET 
//

package com.drighetto.jaxb.vo;

import com.drighetto.jaxb.StockAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;book&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name=&quot;author&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                   &lt;element name=&quot;title&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                   &lt;element name=&quot;genre&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                   &lt;element name=&quot;price&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot;/&gt;
 *                   &lt;element name=&quot;publish_date&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}date&quot;/&gt;
 *                   &lt;element name=&quot;description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *                   &lt;element name=&quot;stock&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name=&quot;id&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "book" })
@XmlRootElement(name = "catalog")
public class Catalog {

	protected List<Catalog.Book> book;

	/**
	 * Gets the value of the book property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the book property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBook().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Catalog.Book }
	 * 
	 * 
	 */
	public List<Catalog.Book> getBook() {
		if (this.book == null) {
			this.book = new ArrayList<Catalog.Book>();
		}
		return this.book;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType&gt;
	 *   &lt;complexContent&gt;
	 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
	 *       &lt;sequence&gt;
	 *         &lt;element name=&quot;author&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *         &lt;element name=&quot;title&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *         &lt;element name=&quot;genre&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *         &lt;element name=&quot;price&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot;/&gt;
	 *         &lt;element name=&quot;publish_date&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}date&quot;/&gt;
	 *         &lt;element name=&quot;description&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
	 *         &lt;element name=&quot;stock&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot;/&gt;
	 *       &lt;/sequence&gt;
	 *       &lt;attribute name=&quot;id&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; /&gt;
	 *     &lt;/restriction&gt;
	 *   &lt;/complexContent&gt;
	 * &lt;/complexType&gt;
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "author", "title", "genre", "price", "publishDate", "description", "available" })
	public static class Book {

		@XmlElement(required = true)
		protected String author;
		@XmlElement(required = true)
		protected String title;
		@XmlElement(required = true)
		protected String genre;
		protected float price;
		@XmlElement(name = "publish_date", required = true)
		@XmlSchemaType(name = "date")
		protected XMLGregorianCalendar publishDate;
		@XmlElement(required = true, defaultValue = "Not desc. available !")
		protected String description;
		@XmlJavaTypeAdapter(StockAdapter.class)
		@XmlElement(name = "stock", required = true)
		protected Boolean available;
		@XmlAttribute
		protected String id;

		/**
		 * Gets the value of the author property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAuthor() {
			return this.author;
		}

		/**
		 * Sets the value of the author property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setAuthor(String value) {
			this.author = value;
		}

		/**
		 * Gets the value of the title property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTitle() {
			return this.title;
		}

		/**
		 * Sets the value of the title property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setTitle(String value) {
			this.title = value;
		}

		/**
		 * Gets the value of the genre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getGenre() {
			return this.genre;
		}

		/**
		 * Sets the value of the genre property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setGenre(String value) {
			this.genre = value;
		}

		/**
		 * Gets the value of the price property.
		 * 
		 */
		public float getPrice() {
			return this.price;
		}

		/**
		 * Sets the value of the price property.
		 * 
		 */
		public void setPrice(float value) {
			this.price = value;
		}

		/**
		 * Gets the value of the publishDate property.
		 * 
		 * @return possible object is {@link XMLGregorianCalendar }
		 * 
		 */
		public XMLGregorianCalendar getPublishDate() {
			return this.publishDate;
		}

		/**
		 * Sets the value of the publishDate property.
		 * 
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 * 
		 */
		public void setPublishDate(XMLGregorianCalendar value) {
			this.publishDate = value;
		}

		/**
		 * Gets the value of the description property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescription() {
			return this.description;
		}

		/**
		 * Sets the value of the description property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setDescription(String value) {
			this.description = value;
		}

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getId() {
			return this.id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setId(String value) {
			this.id = value;
		}

		/**
		 * Getter for the attribute available (This public getter is for users)
		 * 
		 * @return The value of available <br>
		 * 
		 */
		public Boolean isAvailable() {
			return this.available;
		}

		/**
		 * Setter for the attribute available
		 * 
		 * @param available The new value
		 */
		public void setAvailable(Boolean available) {
			this.available = available;
		}

	}

}
