//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.10 at 08:06:23 PM CET 
//

package com.drighetto.jaxb.vo;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.drighetto.jaxb.vo package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.drighetto.jaxb.vo
	 * 
	 */
	public ObjectFactory() {
		// No code
	}

	/**
	 * Create an instance of {@link Catalog }
	 * 
	 */
	public Catalog createCatalog() {
		return new Catalog();
	}

	/**
	 * Create an instance of {@link Catalog.Book }
	 * 
	 */
	public Catalog.Book createCatalogBook() {
		return new Catalog.Book();
	}

}
